version: '3.7'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - data:/data/postgres
volumes:
  data: ./data
